### PR TITLE
Implementation of byte type. 

### PR DESCRIPTION
**Pull request by toneill818**
Added the byte type. Not sure if we want to have signed and unsigned bytes. Also is the precision of a byte dependent on the architecture or should it always be 8? This code was tested and successfully lexed and parsed the following code.

`def main() -> int { var byte a; return 0; }`

### CODE REVIEW

**Comment by asutton** [comment]
The size of a byte depends on the architecture. It just needs to be bigger than 8 bits.

**Comment by Jenny-fa** [comment]
@toneill818:

> Not sure if we want to have signed and unsigned bytes.

IIRC, the concept of signedness in relation to bytes is semantically meaningless; a byte is simply a contiguous sequence of bits. However, both unsigned _and_ signed bytes have been implemented by other languages: [.NET defines `byte` as an unsigned integer](https://msdn.microsoft.com/en-us/library/system.byte%28v=vs.110%29.aspx) (.NET has an [`sbyte` data type](https://msdn.microsoft.com/en-us/library/system.sbyte%28v=vs.110%29.aspx) as well), and [Java defines `byte` as signed](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html).

> Also is the precision of a byte dependent on the architecture or should it always be 8?

On most platforms, a byte is 8 bits (this is actually [a requirement of POSIX.1-2008](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_84); platforms with different byte widths are not, by definition, POSIX-compliant). For true cross-platform compatibility, however, one must always be mindful of the fact that a byte may be as large as 64 bits (!).

@asutton:

> The size of a byte depends on the architecture. It just needs to be bigger than 8 bits.

... Don't you mean "at least," not "bigger than"?

**Comment by asutton** [comment]
> Not sure if we want to have signed and unsigned bytes.
> 
> IIRC, the concept of signedness in relation to bytes is semantically
> meaningless; a byte is simply a contiguous sequence of bits. However, both
> unsigned _and_ signed bytes have been implemented by other languages: .NET
> defines byte as an unsigned integer
> https://msdn.microsoft.com/en-us/library/system.byte%28v=vs.110%29.aspx
> (.NET has an sbyte data type
> https://msdn.microsoft.com/en-us/library/system.sbyte%28v=vs.110%29.aspx
> as well), and Java defines byte as signed
> https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html
> .

I would treat byte as if unsigned for the purpose of useful arithmetic
expressions.

> Also is the precision of a byte dependent on the architecture or should it
> always be 8?
> 
> On most platforms, a byte is 8 bits (this is actually a requirement of
> POSIX.1-2008
> http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_84;
> platforms with different byte widths are not, by definition,
> POSIX-compliant). For true cross-platform compatibility, however, one must
> always be mindful of the fact that a byte may be as large as 64 bits (!).

So, we have a condition under which a freestanding implementation could not
provide a POSIX-compatible runtime. That's okay.

On a side note, all binary network protocols are defined in terms of
octets. I wonder how you parse network buffers with a 9-bit byte. A good
thought exercise, but not something we need to spend too much time
considering.

> The size of a byte depends on the architecture. It just needs to be bigger
> than 8 bits.
> 
> ... Don't you mean "at least," not "bigger than"?
> 
> Oops. right.

**Comment by Jenny-fa** [comment]
> On a side note, all binary network protocols are defined in terms of octets.

The term "octet" is used to disambiguate them from bytes for precisely this reason.

> I wonder how you parse network buffers with a 9-bit byte. A good thought exercise, but not something we need to spend too much time considering.

... That's something I'd rather not contemplate at the moment. :weary:

**Pull request merged**
